# See docs https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    enabled_locales: ['en', 'pt_br']
    default_locale: pt_br
    http_method_override: true
    secret: '%env(APP_SECRET)%'
    serializer:
        enable_annotations: true
    csrf_protection: false
    php_errors:
        log: true
    router:
        strict_requirements: null
    session:
        use_cookies: false
        handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler
    test: ~
