# See docs https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    rate_limiter:
        per_resource:
            policy: 'sliding_window'
            limit: 100
            interval: '1 minutes'
            cache_pool: 'rate_limiter.cache'
        per_user:
            policy: 'sliding_window'
            limit: 1200
            interval: '15 minutes'
            cache_pool: 'rate_limiter.cache'
        per_api:
            policy: 'sliding_window'
            limit: 2400
            interval: '15 minutes'
            cache_pool: 'rate_limiter.cache'
