controllers:
    resource: ../../src/Controller/
    type: annotation

api_v1_controllers:
    resource: ../../src/Api/V1/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
